### ISSUE TITLE
Merge type and format CLI arguments

### ISSUE THREAD

**Issue by javihernandez** [AlmaLinux/alma-sbom#5]
As @ezamriy recommended earlier today, we should merge _type_ and _format_ CLI arguments into one instead of having 2 different arguments. This way, we can just pass `cyclonedx-xml` or `cyclonedx-json`

**Comment by soksanichenko** [comment]
Implemented

**Comment by javihernandez** [comment]
Fixed in https://github.com/AlmaLinux/alma-sbom/commit/5a1b822a15067dc83f8bfb81abff4c7a05a75b39
